### ISSUE TITLE
Cannot change local folder for notes

### ISSUE THREAD

**Issue by glow12121** [appml/nano#10]
I recently updated my OS to Lineage OS 18.1 , based on Android 11. The previous system was MIUI based on Android 6. After this, I haven't been able to set up an operational folder for the app. When I tap on the respective setting, it just displays the default folder address at the bottom of the screen.

Can the folder be changed?

**Comment by appml** [comment]
Due to restrictions imposed by new versions of Android, the app can only access its assigned default app specific location.  

To work with 3rd party folder sync apps, consider creating a folder that mirrors the content of the local repository as described below:

https://appml.github.io/nano/#mirror

Hope this helps.

**Comment by glow12121** [comment]
> Due to restrictions imposed by new versions of Android, the app can only access its assigned default app specific location.
> 

I was wondering why cannot the application work in a user-specified folder by default, instead of using one "local repository" folder and one "mirror" folder.

A problem with the mirror folder is that it is a backup assembled only one per day, while I personally need a synced folder that would be up to date.

And a problem with the local repository is that it cannot be synced.

By the way, the application [manual](https://appml.github.io/nano/) contains a link to "Neutrinote Connector Plus", an add-on that is no longer available on Google Play.

**Comment by appml** [comment]
neutriNote can only see system assigned folder, 3rd party sync apps their respective assigned folders as well.  Mirror belongs to scope storage (technically not a real folder) which any app can see, therefore allowing sync by 3rd party apps.  Mirror got sync in the background whenever it's safe for the data to do so though a smart algorithm, in addition to its nightly routine.  You can also manually trigger a mirror sync by pull to refresh at the list view.

**Comment by glow12121** [comment]
I set up a mirror folder, called "mirror", yesterday and have just tried pulling down in the list view but the folder is still empty, somehow.

phone / Dropsyncfiles / mirror

**Comment by appml** [comment]
1. Toggle Auto Backup under Settings
2. Create mirror folder
3. Use Mirror Files under main list menu
4. Tap Force Sync to establish the mirror for the first time 
![Screenshot_20220618-060853](https://user-images.githubusercontent.com/7504229/174433283-ae0e7a7c-40e9-4efa-8821-938ef8fbcd93.png)

**Comment by glow12121** [comment]
@appml many thanks, will try this.

**Comment by glow12121** [comment]
An off-topic question. Is there possibly a very easy way to sync one's notes via Dropbox that I am missing?

**Comment by glow12121** [comment]
The application exports notes as a backup, each time putting them in a separate folder. Is there a way to make the application maintain a single folder with up to date notes? Basically, I need a single folder to sync between the phone and PCs via Dropbox.

![Screenshot_20220620-031401_Files](https://user-images.githubusercontent.com/29035180/174505758-f932a008-6e0a-4375-9543-65ec5eca90fa.png)

Auto backup/mirror is enabled but there is no Mirror option on the main list menu.

![IMG_20220620_032035](https://user-images.githubusercontent.com/29035180/174506047-7f270ad0-1863-4a35-a73d-c31c1befe209.jpg)

**Comment by appml** [comment]
I think there is a misunderstanding of the concept of mirror.  Rather consider mirror to be a on-going backup copy, so instead of creating a mirror folder holding backups, create a backup folder holding backup copies including mirror as a special type of backup (to which two way sync should occur).  

![Screenshot_20220620-082321](https://user-images.githubusercontent.com/7504229/174601015-13a4f27f-be27-42fc-9aa5-7f556bd7f084.png)

Hope this helps.

**Comment by glow12121** [comment]
Now I got it. This method worked but the application created duplicates of all files with titles such as `*.md (1)`.

I certainly am able to delete the duplicate notes from within the phone. But when I delete them on my PCs and then sync, the unwanted notes stay on the phone. This must have to do with how the mirroring mechanism works. Looks like synchronization doesn't work backwards, from the cloud to the phone.

I use Dropsync, a third party Dropbox application, to synchronize Android files with my PCs.

**Comment by appml** [comment]
The mirroring process could take a while to finish as it is using something called "scoped storage" provided by the operating system, which is slower than ordinary files.  Mirror also handles two way sync.  The duplicate entries could be a result of the first sync of mirror being interrupted.

**Comment by glow12121** [comment]
I deleted the main repository and the mirror, and added the notes anew - it worked this time. Synchronization works both ways. Thank you.

IMHO, it would be easier to use a single selected folder instead of a repository and a mirror, even if the single folder would be "not really a folder". Who cares.

**Comment by appml** [comment]
Agreed.  A single repo would be ideal.  But the speed of scoped storage (on which mirror is based) is not there yet for smooth user interaction (imagine how long it will take to save note changes directly to mirror instead of repo), although Google is making app developers to adopt while blocking access to regular folders.

In any case, if there is ever a need for ongoing, continuous backup, mirror is designed for that, even you use repo instead of mirror for syncing to Dropbox.

**Comment by glow12121** [comment]
> In any case, if there is ever a need for ongoing, continuous backup, mirror is designed for that, even you use repo instead of mirror for syncing to Dropbox.

I would say mirroring and backup functionality would be more convenient when separated. E. g., so the user is able to turn backups off but keep the mirror. That's just based on my experience.
